import {
    Stethoscope, Clock, HeartPulse, Brain, Moon, Activity,
    Scale, Gavel, FileSearch, Eye, ShieldAlert,
    GraduationCap, Users, BookOpen, Bell, MessageCircle, Volume2,
    Briefcase, ClipboardList, TrendingUp, MessageSquare, UserMinus,
} from "lucide-react";

export const PROFESSION_CONFIGS = {
    doctors: {
        slug: "doctors",
        audience: "doctors",
        eyebrowIcon: Stethoscope,
        eyebrowLabel: "Let It Go · Doctors mode",
        hero: {
            pre: "For the people\nwho hold",
            gradient: "everyone else",
            post: ".",
            sub: "An emotional intelligence operating system, tuned for the unique stressors of medicine. Pre-shift readiness, between-patient resets, post-shift decompression — and a long-arc signal for burnout, on your wrist.",
            seeAllLabel: "See the full platform",
        },
        stats: [
            { v: "63%", l: "of US physicians report at least one burnout symptom" },
            { v: "2.3×", l: "higher suicide risk than the general population" },
            { v: "4.5h", l: "average cortisol elevation after a 12-hour shift" },
            { v: "0", l: "tools built around the physician's nervous system. Until now." },
        ],
        stressorsTitle: { pre: "Four invisible ", gradient: "weights", post: "\nnobody trained you for." },
        stressorsEyebrow: "We know what you carry",
        stressors: [
            { icon: Clock, title: "Post-shift residue", text: "You leave the hospital but the shift doesn't leave you. Cortisol stays high for hours after the last alarm." },
            { icon: HeartPulse, title: "Compassion fatigue", text: "Empathy spent on twelve patients today. Almost none left for the person you go home to." },
            { icon: Brain, title: "Decision wear", text: "Two hundred micro-judgements before lunch. The cognitive bill arrives as irritation, brain fog, insomnia." },
            { icon: Moon, title: "Disrupted rhythm", text: "Nights, swings, weekends. Your circadian clock is in pieces — and your nervous system pays the rent." },
        ],
        modulesEyebrow: "Tuned for medicine",
        modulesTitle: { pre: "A clinical-grade companion,\n", gradient: "on the inside", post: " of the white coat." },
        modules: [
            { title: "Pre-shift readiness", text: "A 60-second voice + HRV read before you scrub in. We tell you what you're carrying so you don't carry it onto the floor.", color: "#5E8BFF" },
            { title: "Between-patient resets", text: "Two slow breaths, framed by your watch. Reduces post-encounter cortisol by ~18% in pilot data.", color: "#FF6FD3" },
            { title: "Post-shift decompression", text: "A guided 7-minute close-out as you walk to the car. Marks the end of the shift in your body, not just on the clock.", color: "#8A4DFF" },
            { title: "Long-arc burnout signal", text: "We watch for the slow drift — sleep affect, vocal flatness, written tone. We flag it early, only to you, never to your employer.", color: "#FF8A5C" },
        ],
        complianceTitle: { pre: "Your nervous system\nis ", gradient: "not", post: " the product." },
        complianceChip: "HIPAA-aligned · SOC 2 Type II in progress",
        compliance: [
            "HIPAA-aligned data handling",
            "On-device sensing — affect never leaves your watch unless you choose",
            "Zero data sale, zero ad surfacing, ever",
            "Audit-grade metadata logs (never content)",
            "BAA available on Practice and Hospital plans",
        ],
        pricingTitle: { pre: "Three ways to ", gradient: "come home", post: "." },
        pricing: [
            { name: "Solo Physician", price: "$29", cadence: "/ month", sub: "For your inner life, between patients.", features: ["Continuous on-watch sensing", "Pre & post-shift routines", "Long-arc burnout signal", "Private — nothing leaves your device"], accent: false },
            { name: "Practice", price: "$24", cadence: "/ physician / month", sub: "For groups of 3–25 clinicians.", features: ["Everything in Solo", "Anonymous aggregate burnout dashboard", "BAA available · HIPAA-aligned", "Founder onboarding for your group"], accent: true },
            { name: "Hospital", price: "Custom", cadence: "", sub: "For wellness programs & residency.", features: ["Everything in Practice", "EHR-adjacent SSO (no PHI exchange)", "On-prem / VPC deployment", "Dedicated clinical-affective engineer"], accent: false },
        ],
        testimonialIcon: Activity,
        testimonialQuote: "I'd close out a code, walk back to the workroom, and not know whether my hands were shaking from coffee, adrenaline, or grief. Let It Go gave me the name. Just a name. That was everything.",
        testimonialAuthor: "Dr. R.M., Emergency Medicine, PGY-3",
        faq: [
            { q: "Is this a clinical decision tool?", a: "No. Let It Go for Doctors is a co-regulation instrument designed alongside physicians and clinical psychologists. It does not diagnose, and is not a medical device." },
            { q: "Will my hospital see my data?", a: "Only if you choose to opt into a hospital wellness program. By default everything is private. Hospital admins on Practice/Hospital plans see only aggregate, anonymous burnout-risk telemetry — never individual content." },
            { q: "Does it work between patients without me opening anything?", a: "Yes — Continuous mode on Apple Watch / Wear OS senses HRV, breath cadence, and voice prosody passively and offers a single haptic nudge when your nervous system is climbing. Designed to never interrupt a code, a procedure, or a difficult conversation." },
            { q: "What about state licensure / insurance / fitness-to-practice?", a: "Your data is yours. It is not subpoena-friendly: we hold no content, and metadata is encrypted at rest with keys you can rotate or destroy. We treat physician affective data with the same care we'd want for our own." },
        ],
        cta: {
            label: "Doctors mode · closed beta",
            title: { pre: "Reserve your seat\nin the ", gradient: "first cohort", post: "." },
            sub: "Opening to a small group of physicians this quarter. Drop your email — we'll write quietly, once, when your invitation is ready.",
            placeholder: "your.name@hospital.org",
            footnote: "HIPAA-aligned · designed alongside ED, IM, and palliative physicians. We won't sell, share, or rent your data, ever.",
            successLabel: "Doctors mode",
        },
        footerBrand: "Doctors",
    },

    attorneys: {
        slug: "attorneys",
        audience: "attorneys",
        eyebrowIcon: Scale,
        eyebrowLabel: "Let It Go · Attorneys mode",
        hero: {
            pre: "For the people\nwho carry",
            gradient: "the verdict",
            post: ".",
            sub: "An emotional intelligence operating system, tuned for adversarial work. Pre-court calm, between-witness resets, ethical-bind detection, and a quiet long-arc signal for the kind of fatigue you bill, but never name.",
            seeAllLabel: "See the full platform",
        },
        stats: [
            { v: "28%", l: "of attorneys screen positive for problem-level anxiety" },
            { v: "21%", l: "for problem-level depression — 2× the US adult average" },
            { v: "33%", l: "report problem drinking, often as nervous-system relief" },
            { v: "0", l: "tools built around the litigator's nervous system. Until now." },
        ],
        stressorsTitle: { pre: "Four ", gradient: "adversarial", post: " weights\nthe bar didn't prepare you for." },
        stressorsEyebrow: "We know what you carry",
        stressors: [
            { icon: Gavel, title: "Adversarial residue", text: "Cross-exam leaves a tone in your body. It follows you into your kid's bedtime story." },
            { icon: ShieldAlert, title: "Ethical binds", text: "The duty to advocate vs. the duty to the court — your nervous system feels the split before your mind does." },
            { icon: FileSearch, title: "Vicarious load", text: "Trauma cases. Custody fights. Discovery you can't unsee. The empathy bill arrives quietly, weeks later." },
            { icon: Eye, title: "Hyper-vigilance", text: "Trained to find the flaw. Off the clock, your nervous system can't tell who's a witness and who's family." },
        ],
        modulesEyebrow: "Tuned for the practice",
        modulesTitle: { pre: "A clinical-grade companion,\n", gradient: "behind the bench", post: ", in the deposition, in the car ride home." },
        modules: [
            { title: "Pre-hearing calm", text: "A 60-second affect read before you stand up. We tell you what your voice will betray, and how to soften it.", color: "#5E8BFF" },
            { title: "Between-witness resets", text: "Two slow breaths between objections. Adversarial cortisol doesn't have to compound across the day.", color: "#FF6FD3" },
            { title: "Ethical-bind detection", text: "When duties pull in opposite directions, your body knows first. We name it, so you can think more clearly.", color: "#8A4DFF" },
            { title: "Long-arc fatigue signal", text: "We watch for the slow drift — sleep affect, vocal flatness, written tone in late-night emails. Flagged only to you.", color: "#FF8A5C" },
        ],
        complianceTitle: { pre: "Your nervous system\nis ", gradient: "privileged", post: ", not the product." },
        complianceChip: "Attorney-client aware · SOC 2 Type II in progress",
        compliance: [
            "Attorney-client privilege-aware data handling",
            "On-device sensing — affect never leaves your watch unless you choose",
            "Zero data sale, zero ad surfacing, ever",
            "Audit-grade metadata logs (never content)",
            "Designed for solo, BigLaw, and in-house counsel alike",
        ],
        pricingTitle: { pre: "Three ways to ", gradient: "rest your case", post: "." },
        pricing: [
            { name: "Solo Counsel", price: "$34", cadence: "/ month", sub: "For your inner life, between matters.", features: ["Continuous on-watch sensing", "Pre & post-hearing routines", "Long-arc fatigue signal", "Private — nothing leaves your device"], accent: false },
            { name: "Firm", price: "$28", cadence: "/ attorney / month", sub: "For firms of 5–100 attorneys.", features: ["Everything in Solo Counsel", "Anonymous aggregate burnout dashboard", "Privilege-aware data architecture", "Founder onboarding for your firm"], accent: true },
            { name: "Enterprise", price: "Custom", cadence: "", sub: "For BigLaw, in-house, public defender's offices.", features: ["Everything in Firm", "SSO + e-billing-adjacent integration", "On-prem / VPC deployment", "Dedicated counsel-affective engineer"], accent: false },
        ],
        testimonialIcon: Gavel,
        testimonialQuote: "I'd win the motion, walk back to the office, and not know whether my hands were shaking from caffeine, the cross, or grief for my client. Let It Go gave me the name. That's the most lawyerly thing I ever learned.",
        testimonialAuthor: "M.S., partner, complex commercial litigation",
        faq: [
            { q: "Is this protected by attorney-client privilege?", a: "Your affective data isn't legal communication, so it isn't privileged in the traditional sense — but we architect as if it were. On-device sensing, encryption at rest, metadata-only logs, and you can wipe everything with one tap." },
            { q: "Will my firm see my data?", a: "Only if you opt into a firm wellness program. By default everything is private. Firm admins on the Firm plan see only anonymous aggregate burnout-risk telemetry — never individual content." },
            { q: "Does it work in court without buzzing?", a: "Yes — Continuous mode is silent by design. The single haptic is calibrated to feel like a watch tap, not a notification. You can also enable Court mode to disable all alerts until you leave the courthouse." },
            { q: "What if I'm subpoenaed?", a: "We hold no content. Metadata is encrypted at rest with keys you can rotate or destroy. There is materially nothing for a subpoena to recover from us — by design." },
        ],
        cta: {
            label: "Attorneys mode · closed beta",
            title: { pre: "Reserve your seat\nin the ", gradient: "first cohort", post: "." },
            sub: "Opening to a small group of attorneys this quarter. Drop your email — we'll write quietly, once, when your invitation is ready.",
            placeholder: "your.name@firm.com",
            footnote: "Privilege-aware · designed alongside litigators, in-house counsel, and public defenders. We won't sell, share, or rent your data, ever.",
            successLabel: "Attorneys mode",
        },
        footerBrand: "Attorneys",
    },

    teachers: {
        slug: "teachers",
        audience: "teachers",
        eyebrowIcon: GraduationCap,
        eyebrowLabel: "Let It Go · Teachers mode",
        hero: {
            pre: "For the people\nwho hold",
            gradient: "thirty rooms at once",
            post: ".",
            sub: "An emotional intelligence operating system, tuned for the classroom. Pre-bell readiness, between-period resets, a quiet read of the room, and a long-arc signal for the burnout the staffroom never lets you name.",
            seeAllLabel: "See the full platform",
        },
        stats: [
            { v: "44%", l: "of K-12 teachers report frequent burnout — highest of any US profession" },
            { v: "8 in 10", l: "say their wellbeing was worse than the year before" },
            { v: "55%", l: "are considering leaving the profession earlier than planned" },
            { v: "0", l: "tools built around the teacher's nervous system. Until now." },
        ],
        stressorsTitle: { pre: "Four ", gradient: "invisible", post: " weights\nthat live between the bells." },
        stressorsEyebrow: "We know what you carry",
        stressors: [
            { icon: Volume2, title: "Sensory load", text: "Thirty conversations, two fluorescent buzzes, a fire drill, a heartbreak in row three. By 10am your nervous system has run a marathon." },
            { icon: MessageCircle, title: "Parent-conf weight", text: "You hold the data, the doubt, and the dignity of the family in front of you. Your jaw remembers, even if you don't." },
            { icon: Users, title: "Co-regulator role", text: "You are the calmest nervous system in the room — for every other nervous system in the room. That math is exhausting." },
            { icon: Bell, title: "Cognitive whiplash", text: "Bell. New room. New subject. New mood. The transitions cost more than the teaching." },
        ],
        modulesEyebrow: "Tuned for the classroom",
        modulesTitle: { pre: "A quiet co-pilot,\n", gradient: "between you and the bell", post: "." },
        modules: [
            { title: "Pre-bell readiness", text: "A 60-second check-in before first period. We tell you what you're carrying so you don't pour it onto Period 1.", color: "#5E8BFF" },
            { title: "Between-period resets", text: "Three slow breaths in the four minutes between rooms. You walk into the next group as yourself, not as the last one's echo.", color: "#FF6FD3" },
            { title: "Parent-conference prep", text: "A 90-second pre-conversation grounding. Name your edge, soften your shoulders, lead with the child.", color: "#8A4DFF" },
            { title: "Long-arc burnout signal", text: "We watch for the slow drift across a semester — sleep affect, vocal flatness, written tone. Flagged only to you, never your principal.", color: "#FF8A5C" },
        ],
        complianceTitle: { pre: "Your nervous system\nis ", gradient: "yours", post: ", not the district's." },
        complianceChip: "FERPA-aware · COPPA-aligned · SOC 2 in progress",
        compliance: [
            "FERPA-aware data handling (no student data is ever collected)",
            "On-device sensing — affect never leaves your watch unless you choose",
            "Zero data sale, zero ad surfacing, ever",
            "Audit-grade metadata logs (never content)",
            "District plan: aggregate, anonymous wellbeing telemetry only",
        ],
        pricingTitle: { pre: "Three ways to ", gradient: "stay in the room", post: "." },
        pricing: [
            { name: "Solo Teacher", price: "$9", cadence: "/ month", sub: "Because we know what you actually make.", features: ["Continuous on-watch sensing", "Pre-bell & period routines", "Long-arc burnout signal", "Private — nothing leaves your device"], accent: false },
            { name: "School", price: "$7", cadence: "/ teacher / month", sub: "For schools of 10–200 educators.", features: ["Everything in Solo Teacher", "Anonymous aggregate wellbeing dashboard", "FERPA-aware architecture", "Founder onboarding for your faculty"], accent: true },
            { name: "District", price: "Custom", cadence: "", sub: "For districts & higher-ed wellbeing programs.", features: ["Everything in School", "SSO + payroll-adjacent SSO", "On-prem / VPC deployment", "Dedicated educator-affective engineer"], accent: false },
        ],
        testimonialIcon: BookOpen,
        testimonialQuote: "Fifth period after a fire drill, I sat in my car for ten minutes before I could go pick up my own kid. Let It Go pinged me at 3:14, said 'you're carrying the building, not yourself.' I cried, then I drove. It was kinder than my whole inbox.",
        testimonialAuthor: "Ms. K., 8th grade humanities, year 11",
        faq: [
            { q: "Will my district see my data?", a: "Only if you opt into a school or district wellbeing program. By default everything is private. Admins on School/District plans see only anonymous aggregate wellbeing telemetry — never individual content." },
            { q: "Does Let It Go collect anything about my students?", a: "No. Ever. The system is designed to sense only your affect, on your device. We are FERPA-aware by architecture — there is nothing about students for us to mishandle." },
            { q: "Will it buzz during class?", a: "Only if you let it. Classroom mode silences all haptics until your prep period. Most teachers leave a single between-period gentle tap on, and disable everything else." },
            { q: "Is this affordable on a teacher's salary?", a: "Yes — that's why Solo Teacher is $9/mo, and we're working on union-discount and Title-I subsidy programs. If $9 is still too much, write to us. We'll figure something out." },
        ],
        cta: {
            label: "Teachers mode · closed beta",
            title: { pre: "Reserve your seat\nin the ", gradient: "first cohort", post: "." },
            sub: "Opening to a small group of teachers this quarter. Drop your email — we'll write quietly, once, when your invitation is ready.",
            placeholder: "your.name@school.org",
            footnote: "FERPA-aware · designed alongside K-12 teachers, special ed, and SEL coordinators. We won't sell, share, or rent your data, ever.",
            successLabel: "Teachers mode",
        },
        footerBrand: "Teachers",
    },

    managers: {
        slug: "managers",
        audience: "managers",
        eyebrowIcon: Briefcase,
        eyebrowLabel: "Let It Go · Managers mode",
        hero: {
            pre: "For the people\nwho hold",
            gradient: "everyone's career",
            post: ".",
            sub: "An emotional intelligence operating system, tuned for management. Pre-1:1 prep, conflict mediation, layoff-conversation support, and a quiet long-arc signal for the burnout your skip-level never sees.",
            seeAllLabel: "See the full platform",
        },
        stats: [
            { v: "71%", l: "of managers say their workload is unsustainable" },
            { v: "1 in 3", l: "are considering leaving management entirely" },
            { v: "59 min", l: "median time between difficult Slack messages" },
            { v: "0", l: "tools built around the manager's nervous system. Until now." },
        ],
        stressorsTitle: { pre: "Four ", gradient: "structural", post: " weights\nnobody promoted you into." },
        stressorsEyebrow: "We know what you carry",
        stressors: [
            { icon: Users, title: "Sandwich pressure", text: "Direct reports above, leadership below — or the other way around — but always you, absorbing both directions of bad news." },
            { icon: UserMinus, title: "Layoff weight", text: "You delivered the news to seven people in two days. Then you went home and your partner asked how work was." },
            { icon: ClipboardList, title: "Decision residue", text: "Every comp band, every PIP, every promo. Each one stays in your body until the next one buries it." },
            { icon: TrendingUp, title: "Performative calm", text: "You are the regulated nervous system in every room. Off the clock, your own dysregulation has nowhere to land." },
        ],
        modulesEyebrow: "Tuned for management",
        modulesTitle: { pre: "A quiet co-pilot,\n", gradient: "in every hard conversation", post: "." },
        modules: [
            { title: "Pre-1:1 prep", text: "A 60-second grounding before your harder check-ins. Name your edge before they walk in.", color: "#5E8BFF" },
            { title: "Mid-meeting resets", text: "A single haptic when your tone hardens. A breath before you escalate. Conflict de-escalation, in your wrist.", color: "#FF6FD3" },
            { title: "Layoff-conversation support", text: "A guided pre- and post- routine for the conversations that matter most. So you show up regulated, and recover after.", color: "#8A4DFF" },
            { title: "Long-arc burnout signal", text: "We watch for the slow drift — sleep affect, vocal flatness, written tone in late-night Slack. Flagged only to you.", color: "#FF8A5C" },
        ],
        complianceTitle: { pre: "Your nervous system\nis ", gradient: "yours", post: ", not your company's." },
        complianceChip: "SSO-friendly · SOC 2 Type II in progress",
        compliance: [
            "Personal account by default — even on company devices",
            "On-device sensing — affect never leaves your watch unless you choose",
            "Zero data sale, zero ad surfacing, ever",
            "Audit-grade metadata logs (never content)",
            "Org plans see only anonymous aggregate manager-load telemetry",
        ],
        pricingTitle: { pre: "Three ways to ", gradient: "lead from the middle", post: "." },
        pricing: [
            { name: "Solo Manager", price: "$19", cadence: "/ month", sub: "Bring your own account. Take it between jobs.", features: ["Continuous on-watch sensing", "Pre-1:1 & mid-meeting routines", "Long-arc burnout signal", "Private — nothing leaves your device"], accent: false },
            { name: "Team", price: "$14", cadence: "/ manager / month", sub: "For management groups of 5–100.", features: ["Everything in Solo Manager", "Anonymous aggregate manager-load dashboard", "SSO + calendar-aware routines", "Founder onboarding for your team"], accent: true },
            { name: "Org", price: "Custom", cadence: "", sub: "For org-wide manager development programs.", features: ["Everything in Team", "HRIS-adjacent (no PII exchange)", "On-prem / VPC deployment", "Dedicated manager-affective engineer"], accent: false },
        ],
        testimonialIcon: MessageSquare,
        testimonialQuote: "I gave six people the layoff news on a Tuesday. I went home and snapped at my kid over a juice box. Let It Go didn't fix me, but it named what was happening before I did something I couldn't take back. That's the whole job, really.",
        testimonialAuthor: "K.A., engineering manager, post-Series-C startup",
        faq: [
            { q: "Will my employer see my data?", a: "Only if you opt into a company management program. By default everything is private and lives in your personal account. Org-plan admins see only anonymous aggregate manager-load telemetry — never individual content." },
            { q: "Can I take my account with me if I change jobs?", a: "Yes. The default is a personal account that travels with you. If you joined via a Team plan, you can convert to Solo Manager on departure and keep your full growth history." },
            { q: "Does it work during 1:1s without my report noticing?", a: "Yes — Continuous mode is silent. The haptic is calibrated to feel like a watch tap. Most managers use Pre-1:1 mode before the call and let Continuous mode quietly catch the moments inside it." },
            { q: "Is this just executive coaching as software?", a: "No. Coaches give you scripts. Let It Go gives you the read of your own nervous system before the hard conversation — and a quiet companion inside of it. They actually pair well together." },
        ],
        cta: {
            label: "Managers mode · closed beta",
            title: { pre: "Reserve your seat\nin the ", gradient: "first cohort", post: "." },
            sub: "Opening to a small group of managers this quarter. Drop your email — we'll write quietly, once, when your invitation is ready.",
            placeholder: "your.name@company.com",
            footnote: "Designed alongside engineering managers, HRBPs, and people leaders. We won't sell, share, or rent your data, ever.",
            successLabel: "Managers mode",
        },
        footerBrand: "Managers",
    },
};
